// Build results/summary.md from results/*.json. `node src/node/report.ts`

import { readFileSync, writeFileSync } from 'node:fs';

// biome-ignore lint/suspicious/noExplicitAny: loose result JSON
const read = (f: string): any => JSON.parse(readFileSync(`results/${f}`, 'utf8'));
const C = ['libcascade', 'replicad', 'brepjs'] as const;
const node = Object.fromEntries(C.map((c) => [c, read(`node-${c}.json`)]));
const browser = read('browser.json');
const sizes = read('sizes.json');
const ms = (v: number) => (v < 10 ? v.toFixed(1) : v.toFixed(0));
const mb = (v: number) => (v / 1e6).toFixed(2);
const med = (xs: number[]) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)];
const table = (head: string[], rows: (string | number)[][]) =>
  [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');

const ops = ['box', 'fillet', 'cut', 'tessellate', 'stl', 'step', 'stepReimport', 'total'];
const lines: string[] = [];
lines.push('# P0-02 results', '');
lines.push(
  `Generated by \`node src/node/report.ts\` from \`results/*.json\`. Node ${node.libcascade.node}, Chromium ${browser.libcascade.browser} (headless, via Playwright), ` +
    'Ryzen 7 4700U laptop. Browser loads are served from localhost by `vite preview`, so network transfer time is not included.',
  '',
);

lines.push('## Size (Vite production build)', '');
lines.push(
  table(
    ['', 'WASM raw', 'WASM gzip', 'WASM brotli', 'JS raw', 'JS brotli'],
    C.map((c) => [c, `${mb(sizes[c].wasm.raw)} MB`, `${mb(sizes[c].wasm.gzip)} MB`, `**${mb(sizes[c].wasm.brotli)} MB**`, `${(sizes[c].js.raw / 1e3).toFixed(0)} kB`, `${(sizes[c].js.brotli / 1e3).toFixed(0)} kB`]),
  ),
  '',
);

lines.push('## Cold load', '');
lines.push(
  table(
    ['', 'Browser: worker spawn → kernel ready (median of 3)', 'of which WASM fetch+compile+init', 'Node: import + init', 'Works without SharedArrayBuffer'],
    C.map((c) => {
      // biome-ignore lint/suspicious/noExplicitAny: loose result JSON
      const loads = browser[c].loads as any[];
      return [
        c,
        `**${ms(med(loads.map((l) => l.workerReadyMs)))} ms**`,
        `${ms(med(loads.map((l) => l.load.initMs)))} ms`,
        `${ms(node[c].coldReadyMs)} ms`,
        loads.every((l) => l.ok && !l.crossOriginIsolated && !l.sharedArrayBuffer) ? 'yes (page not cross-origin isolated)' : 'NO',
      ];
    }),
  ),
  '',
);

lines.push('## Time per operation (ms)', '');
lines.push('First run after init (cold JIT) / median of warm runs (10 in Node, 5 in the browser worker).', '');
lines.push(
  table(
    ['op', ...C.map((c) => `${c} Node`), ...C.map((c) => `${c} browser`)],
    ops.map((op) => [
      op,
      ...C.map((c) => `${ms(node[c].first[op])} / ${ms(node[c].warmMedian[op])}`),
      ...C.map((c) => `${ms(browser[c].loads[0].result.timings[op])} / ${ms(browser[c].loads[0].warmMedian[op])}`),
    ]),
  ),
  '',
);

lines.push('## Result checks', '');
lines.push(
  table(
    ['', 'valid', 'volume (expected 22840.18)', 'faces / edges', 'triangles', 'STL bytes', 'STL watertight', 'STEP bytes', 'STEP re-import faces / volume'],
    C.map((c) => {
      const k = node[c].checks;
      return [c, k.valid, k.volume.toFixed(2), `${k.faces} / ${k.edges}`, k.triangles, k.stlBytes, k.stlWatertight, k.stepBytes, `${k.stepReimportFaces} / ${k.stepReimportVolume.toFixed(2)}`];
    }),
  ),
  '',
);

lines.push('## Memory: rebuild box → fillet → cut → mesh with disposal', '');
lines.push(
  table(
    ['', 'iterations', 'WASM heap: start → end', 'growth per rebuild', 'live shapes at end', 'leak control (no disposal) grows?'],
    C.map((c) => {
      const m = node[c].memory;
      const h = (x: number) => `${(x / 1048576).toFixed(0)} MB`;
      const lc = m.leakControl;
      const grows = lc.at(-1).heapBytes > lc[0].heapBytes || (lc.at(-1).liveShapes ?? 0) > (lc[0].liveShapes ?? 0);
      return [c, m.iterations, `${h(m.samples[0].heapBytes)} → ${h(m.samples.at(-1).heapBytes)}`, `**${m.kbPerIter.toFixed(1)} KB**`, m.samples.at(-1).liveShapes ?? 'n/a', grows ? 'yes' : 'no'];
    }),
  ),
  '',
);

lines.push('## Topological-naming feasibility (history through fillet → cut)', '');
lines.push(
  table(
    ['', 'layer', 'tracks faces / edges', 'final faces named from history', 'final edges named from history', 'edges named from adjacent faces'],
    C.map((c) => {
      const h = node[c].history;
      return [c, node[c].layer, `${h.tracks.faces} / ${h.tracks.edges}`, `${h.coverage.faces.named} / ${h.coverage.faces.total}`, `${h.coverage.edges.named} / ${h.coverage.edges.total}`, h.coverage.edges.derived];
    }),
  ),
  '',
);
for (const c of C) {
  lines.push(`### ${c}`, '', '```', ...node[c].history.lines, '```', '');
  lines.push(`Final faces: ${node[c].history.finalFaces.map((f: { index: number; names: string[] }) => `${f.index}=${f.names.join('+') || '∅'}`).join(', ')}`, '');
  for (const n of node[c].history.notes) lines.push(`- ${n}`);
  lines.push('');
}
writeFileSync('results/summary.md', lines.join('\n'));
console.log(lines.join('\n'));
