// Shared result shapes for the P0-02 kernel spike. Every candidate returns a
// ScenarioResult so Node and the browser page can print the same table.

export type CandidateId = 'libcascade' | 'replicad' | 'brepjs' | 'custom';

/** Scenario parameters (fixed by the roadmap task). */
export const SCENARIO = {
  box: [40, 30, 20] as const,
  filletRadius: 3,
  holeDiameter: 8,
  /** Tessellation: linear deflection (mm) and angular deflection (rad). */
  linDefl: 0.05,
  angDefl: 0.3,
};

/** Analytic volume of the scenario solid, for sanity checks. */
export function expectedVolume(): number {
  const [x, y, z] = SCENARIO.box;
  const r = SCENARIO.filletRadius;
  const filletLoss = 4 * (r * r - (Math.PI * r * r) / 4) * z;
  const hole = Math.PI * (SCENARIO.holeDiameter / 2) ** 2 * z;
  return x * y * z - filletLoss - hole;
}

export interface MeshData {
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  /** Pairs [firstTriangle, triangleCount] per B-rep face, in face order. */
  faceRanges: Uint32Array;
  /** One polyline (xyz triples) per B-rep edge. */
  edges: Float32Array[];
}

export interface Timings {
  box: number;
  fillet: number;
  cut: number;
  tessellate: number;
  stl: number;
  step: number;
  stepReimport: number;
  total: number;
}

export interface HistoryReport {
  /** Can this candidate report per-operation history at all? */
  available: boolean;
  /** Which topology kinds are tracked through history. */
  tracks: { faces: boolean; edges: boolean };
  /** Human-readable "original → result" lines for fillet then cut. */
  lines: string[];
  /** Final-solid coverage: how many faces/edges got a persistent name from history. */
  coverage: {
    faces: { total: number; named: number; ambiguous: number };
    /** named = got a history name; derived = named from its two adjacent faces; multiNamed = several history names (e.g. an intersection edge generated by two faces). */
    edges: { total: number; named: number; derived: number; multiNamed: number };
  };
  /** Final face names, in face order (index = face index in the final solid). */
  finalFaces: { index: number; area: number; names: string[] }[];
  /** Final edge names (history names, or the derived adjacent-face name in brackets). */
  finalEdges?: { index: number; length: number; names: string[] }[];
  notes: string[];
}

export interface Checks {
  valid: boolean;
  volume: number;
  expectedVolume: number;
  faces: number;
  edges: number;
  triangles: number;
  stlBytes: number;
  stlWatertight: boolean;
  stlVolume: number;
  stepBytes: number;
  stepSchema: string;
  stepReimportFaces: number;
  stepReimportVolume: number;
}

export interface ScenarioResult {
  candidate: CandidateId;
  /** Which layer the scenario ran through (e.g. "replicad API" or "raw OCCT via getOC()"). */
  layer: string;
  timings: Timings;
  checks: Checks;
  history: HistoryReport;
  mesh: MeshData;
  stl: Uint8Array;
  step: Uint8Array;
}

export interface LoadResult {
  candidate: CandidateId;
  initMs: number;
  /** Size of the WASM heap right after init, in bytes. */
  heapBytes: number;
}
