// Builds results/summary.md from the raw result files.
// biome-ignore-all lint/suspicious/noExplicitAny: loose result JSON
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../../results/', import.meta.url);
const read = (name: string): any =>
  existsSync(new URL(name, dir)) ? JSON.parse(readFileSync(new URL(name, dir), 'utf8')) : undefined;
const ms = (n: number | undefined) =>
  n === undefined ? '–' : n >= 100 ? n.toFixed(0) : n >= 10 ? n.toFixed(1) : n.toFixed(2);

const lines: string[] = [
  '# P0-03 solver spike: results',
  '',
  'Generated by `node src/node/report.ts` from `results/*.json`. Milliseconds unless',
  'noted; medians, with p95 after a slash where measured. One laptop (Ryzen 7 4700U).',
  '"Entities" are lines, arcs and circles; "unknowns" are the free solver parameters.',
  '',
];

for (const build of ['npm', 'growth']) {
  const data = read(`node-${build}.json`);
  if (!data) continue;
  lines.push(
    `## One planegcs system per sketch, \`${build}\` build (${data.runtime})`,
    '',
    build === 'npm'
      ? 'The published package. Its heap is fixed at 16 MB: "OOM" is an out-of-memory abort.'
      : 'Our build with `ALLOW_MEMORY_GROWTH` (otherwise the upstream toolchain).',
    '',
    '| Layout | Join | Entities | Unknowns | First solve | Drag step | Rebuild + solve | Dimension change | Constraint edit (rebuild + diagnose) | Conflict: reported, culprit found |',
    '|---|---|---|---|---|---|---|---|---|---|',
  );
  for (const r of data.results) {
    if (r.error) {
      lines.push(`| ${r.layout} | ${r.join} | ${r.entities} | | OOM | | | | | |`);
      continue;
    }
    lines.push(
      `| ${r.layout} | ${r.join} | ${r.entities} | ${r.params} | ${ms(r.firstSolve)} | ${ms(r.drag.median)} / ${ms(r.drag.p95)} | ${ms(r.dragRebuild.median)} | ${ms(r.paramChange.median)} | ${ms(r.conflict.solve)} | ${r.conflict.reported}, ${r.conflict.includesCulprit ? 'yes' : 'no'} |`,
    );
  }
  lines.push(
    '',
    'First solve starts from ±2 mm noise on every point and includes the diagnosis. "Drag step" updates two',
    'parameters and re-solves (temporary constraints, SQP). "Constraint edit" is the solve after adding a',
    'constraint (here a conflicting one), which re-runs the diagnosis.',
    '',
  );
}

for (const build of ['npm', 'growth']) {
  const data = read(`components-${build}.json`);
  if (!data) continue;
  lines.push(
    `## One planegcs system per independent component, \`${build}\` build`,
    '',
    'The anchored sketches, split with `src/components.ts`.',
    '',
    '| Join | Entities | Components | Largest (unknowns) | Open (build + solve all) | Drag step | Constraint edit | Dimension change (all components) |',
    '|---|---|---|---|---|---|---|---|',
  );
  for (const r of data.results) {
    lines.push(
      `| ${r.join} | ${r.entities} | ${r.components} | ${r.largestUnknowns} | ${ms(r.firstSolveAll)} | ${ms(r.drag.median)} / ${ms(r.drag.p95)} | ${ms(r.constraintEdit.median)} | ${ms(r.paramChange.median)} |`,
    );
  }
  lines.push('');
}

const compare = read('compare.json');
if (compare) {
  lines.push(
    '## Our builds on one large system (coincident joins)',
    '',
    '`growth`: upstream toolchain + memory growth. `modern`: emsdk 6.0.10 + SIMD.',
    '`fast`: `modern` + LeastNormLdlt DogLeg step + column-pivoting QR in the SQP step.',
    '',
    '| Build | Layout | Entities | First solve | Drag step | Dimension change |',
    '|---|---|---|---|---|---|',
  );
  for (const r of compare) {
    lines.push(
      `| ${r.solverBuild} | ${r.layout} | ${r.entities} | ${ms(r.firstSolve)} | ${ms(r.drag.median)} | ${ms(r.paramChange.median)} |`,
    );
  }
  lines.push('');
}

const browser = read('browser.json');
if (browser) {
  lines.push(
    `## Browser (headless Chromium ${browser.browser}, main thread)`,
    '',
    'Dragging the free corner for 180 animation frames. Generated sketches are split into components; only',
    'the dragged one is re-solved. "Slow frames" took more than 1.5 frame budgets.',
    '',
    '| Build | Sketch | Layout | Components | Solve per frame | Frame rate | Slow frames |',
    '|---|---|---|---|---|---|---|',
  );
  for (const build of ['npm', 'fast']) {
    const b = browser[build];
    if (!b) continue;
    const row = (r: any) =>
      r.error
        ? `| ${build} | ${r.sketch} entities | ${r.layout} | | ${r.error.includes('OOM') ? 'OOM' : 'error'} | | |`
        : `| ${build} | ${r.sketch === 'rect' ? 'rectangle' : `${r.sketch} entities`} | ${r.sketch === 'rect' ? '–' : r.layout} | ${r.components} | ${ms(r.solveMedian)} / ${ms(r.solveP95)} | ${r.fps.toFixed(0)} fps | ${r.framesOver16ms} |`;
    lines.push(row(b.rectangle));
    for (const d of b.drags) lines.push(row(d));
  }
  const c = browser.npm?.conflictState;
  if (c) {
    lines.push(
      '',
      `Rectangle with a second width: DOF ${c.dof}, solve status ${c.status}, conflicting: ${c.conflicts.join(', ')}.`,
    );
  }
  lines.push('');
}

const slvs = read('slvs.json');
if (slvs) {
  const r = slvs.results[0];
  lines.push(
    `## SolveSpace (${slvs.package})`,
    '',
    `Anchored ${r.entities} entities (${r.unknowns} unknowns): first solve ${ms(r.first)}, drag step (rebuild + solve) ${ms(r.dragRebuild)}, conflicting dimension ${ms(r.conflict.ms)} (${r.conflict.bad} reported). ${slvs.note}`,
    '',
  );
}

writeFileSync(new URL('summary.md', dir), `${lines.join('\n')}\n`);
console.log(`wrote results/summary.md (${lines.length} lines)`);
