// Extrudo's trimmed OCCT WASM build (ADR-0001), made with @libcascade/toolchain.
// Built by `pnpm occt build` (needs Docker and the pinned 2.4 GB
// ghcr.io/taucad/opencascade.js image, about 10 minutes), or downloaded by
// `pnpm occt ensure` from the GitHub release that CI publishes for the current
// inputs. See packages/kernel/occt/README.md.
//
// `bindings` is the raw OCCT surface for read-only queries and prototyping,
// plus our C++ facade (facade/extrudo_facade.cpp), which owns OCCT memory and
// does all heavy work (taucad/opencascade.js#40).
import { defineBuild } from '@libcascade/toolchain';

export default defineBuild({
  name: 'extrudo_occt',
  // biome-ignore format: one line per topic is easier to review than one symbol per line
  bindings: [
    // our facade (facade/extrudo_facade.cpp)
    'ExtrudoFacade',
    // geometry primitives
    'gp_Pnt', 'gp_Dir', 'gp_Vec', 'gp_Ax1', 'gp_Ax2', 'gp_Ax3', 'gp_Pln', 'gp_Trsf', 'gp_Pnt2d', 'gp_Dir2d',
    'gp_Circ', 'gp_Lin',
    // topology
    'TopoDS', 'TopoDS_Shape', 'TopoDS_Face', 'TopoDS_Edge', 'TopoDS_Wire', 'TopoDS_Vertex', 'TopoDS_Shell',
    'TopoDS_Solid', 'TopoDS_Compound', 'TopExp', 'TopExp_Explorer', 'TopLoc_Location', 'BRep_Tool', 'BRep_Builder',
    'TopTools_ShapeMapHasher', 'NCollection_BaseMap', 'NCollection_BaseList',
    // builders and features
    'BRepBuilderAPI_MakeShape', 'BRepBuilderAPI_MakeEdge', 'BRepBuilderAPI_MakeWire', 'BRepBuilderAPI_MakeFace',
    'BRepBuilderAPI_Transform', 'BRepPrimAPI_MakeBox', 'BRepPrimAPI_MakeCylinder', 'BRepPrimAPI_MakePrism',
    'BRepPrimAPI_MakeRevol', 'BRepOffsetAPI_MakePipeShell', 'BRepOffsetAPI_ThruSections',
    'BRepOffsetAPI_MakeThickSolid', 'BRepFilletAPI_MakeFillet', 'BRepFilletAPI_MakeChamfer',
    'BRepAlgoAPI_Fuse', 'BRepAlgoAPI_Cut', 'BRepAlgoAPI_Common', 'BRepAlgoAPI_BuilderAlgo', 'BOPAlgo_Builder',
    'BRepTools_History', 'GC_MakeArcOfCircle', 'GC_MakeSegment', 'Geom_Curve', 'Geom_Surface',
    // meshing, measurement, checks, healing
    'BRepMesh_IncrementalMesh', 'Poly_Triangulation', 'Poly_PolygonOnTriangulation', 'BRepGProp', 'GProp_GProps',
    'BRepCheck_Analyzer', 'BRepBndLib', 'Bnd_Box', 'BRepAdaptor_Surface', 'BRepAdaptor_Curve',
    'ShapeFix_Shape', 'ShapeUpgrade_UnifySameDomain',
    // exchange
    'STEPControl_Writer', 'STEPControl_Reader', 'STEPControl_StepModelType', 'Interface_Static',
    'Message_ProgressRange', 'StlAPI_Writer',
    // enums and collections the spike touches (found by `npx libcascade check ../src`)
    'TopAbs_ShapeEnum', 'TopAbs_Orientation', 'ChFi3d_FilletShape',
    'NCollection_IndexedMap_TopoDS_Shape_TopTools_ShapeMapHasher', 'NCollection_List_TopoDS_Shape',
    // Generated by `node closure.mjs --refs`: base classes of the above (embind
    // refuses to construct a class whose base is unbound) and the types their
    // APIs reference directly. `libcascade check` cannot see these.
    'Adaptor3d_Curve', 'Adaptor3d_Surface', 'Approx_ParametrizationType', 'BOPAlgo_Algo',
    'BOPAlgo_BuilderShape', 'BOPAlgo_GlueEnum', 'BOPAlgo_Operation', 'BOPAlgo_Options', 'BOPDS_DS',
    'BRepAlgoAPI_Algo', 'BRepAlgoAPI_BooleanOperation', 'BRepBuilderAPI_Command',
    'BRepBuilderAPI_EdgeError', 'BRepBuilderAPI_FaceError', 'BRepBuilderAPI_ModifyShape',
    'BRepBuilderAPI_PipeError', 'BRepBuilderAPI_TransitionMode', 'BRepBuilderAPI_WireError',
    'BRepCheck_Result', 'BRepFill_ThruSectionErrorStatus', 'BRepFill_TypeOfContact',
    'BRepFilletAPI_LocalOperation', 'BRepMesh_DiscretRoot', 'BRepOffsetAPI_MakeOffsetShape',
    'BRepOffset_Mode', 'BRepPrimAPI_MakeOneAxis', 'BRepPrimAPI_MakeSweep', 'BRepPrim_Cylinder',
    'BRepPrim_GWedge', 'BRepPrim_OneAxis', 'BRepPrim_Revolution', 'BRepPrim_Wedge',
    'BRepSweep_Prism', 'BRepSweep_Revol', 'Bnd_OBB', 'ChFiDS_ChamfMode', 'ChFiDS_ErrorStatus',
    'GC_Root', 'GProp_PrincipalProps', 'Geom2d_Curve', 'Geom2d_Geometry', 'GeomAbs_JoinType',
    'GeomAbs_Shape', 'GeomAdaptor_TransformedCurve', 'GeomAdaptor_TransformedSurface',
    'Geom_BoundedCurve', 'Geom_Geometry', 'Geom_TrimmedCurve', 'IFSelect_ReturnStatus',
    'IFSelect_WorkSession', 'IMeshData_Shape', 'IMeshTools_Context', 'IMeshTools_Parameters',
    'IntTools_Context', 'Interface_InterfaceModel', 'Interface_ParamType', 'Interface_TypedValue',
    'Law_Function', 'Message_Report', 'MoniTool_TypedValue',
    'NCollection_Array1_NCollection_Vec3_float', 'NCollection_Array1_Poly_Triangle',
    'NCollection_Array1_double', 'NCollection_Array1_gp_Pnt', 'NCollection_Array1_gp_Pnt2d',
    'NCollection_Array1_int', 'NCollection_BaseAllocator', 'NCollection_BaseSequence',
    'NCollection_DataMap_TCollection_AsciiString_TCollection_AsciiString',
    'NCollection_DataMap_TopoDS_Shape_NCollection_List_TopoDS_Shape_TopTools_ShapeMapHasher',
    'NCollection_DataMap_TopoDS_Shape_TopoDS_Shape_TopTools_ShapeMapHasher',
    'NCollection_ForwardRangeSentinel', 'NCollection_HArray1_ChFiDS_CircSection',
    'NCollection_HArray1_Poly_Triangle', 'NCollection_HArray1_double', 'NCollection_HArray1_float',
    'NCollection_HArray1_gp_Pnt', 'NCollection_HArray1_gp_Pnt2d',
    'NCollection_HSequence_handle_TCollection_HAsciiString',
    'NCollection_IndexedDataMap_TopoDS_Shape_NCollection_List_TopoDS_Shape_TopTools_ShapeMapHasher',
    'NCollection_List_handle_Poly_Triangulation',
    'NCollection_Map_TopoDS_Shape_TopTools_ShapeMapHasher',
    'NCollection_Sequence_TCollection_AsciiString', 'Poly_ArrayOfNodes', 'Poly_ArrayOfUVNodes',
    'Poly_Polygon2D', 'Poly_Polygon3D', 'Poly_Triangle', 'Poly_TriangulationParameters',
    'ShapeExtend_BasicMsgRegistrator', 'ShapeExtend_Status', 'ShapeFix_Edge', 'ShapeFix_Face',
    'ShapeFix_Root', 'ShapeFix_Shell', 'ShapeFix_Solid', 'ShapeFix_Wire', 'Standard_Transient',
    'Standard_Type', 'StepData_StepModel', 'TopAbs_State', 'TopLoc_Datum3D', 'TopoDS_Builder',
    'TopoDS_TShape', 'XSControl_Reader', 'XSControl_WorkSession', 'gp_Ax2d', 'gp_Cone',
    'gp_Cylinder', 'gp_Elips', 'gp_GTrsf2d', 'gp_Hypr', 'gp_Mat', 'gp_Parab', 'gp_Quaternion',
    'gp_Sphere', 'gp_Torus', 'gp_Trsf2d', 'gp_TrsfForm', 'gp_Vec2d', 'gp_XY', 'gp_XYZ',
  ],
  customBindings: [{ file: 'facade/extrudo_facade.cpp', symbols: ['ExtrudoFacade'] }],
  settings: {
    // An ES-module factory; libcascade's assembled init.js imports the glue as ESM.
    MODULARIZE: true,
    EXPORT_ES6: true,
    ALLOW_MEMORY_GROWTH: true,
    // With -fwasm-exceptions the toolchain requires the three exception helpers.
    EXPORTED_RUNTIME_METHODS: [
      'FS',
      'wasmMemory',
      'getExceptionMessage',
      'incrementExceptionRefcount',
      'decrementExceptionRefcount',
    ],
    ENVIRONMENT: ['web', 'worker', 'node'],
  },
  compilerFlags: { exceptions: 'wasm', noEntry: true, simd: true, optimize: 'O3' },
  variants: [{ name: 'single' }],
});
