/**
 * The generator behind `pnpm api:generate` (ADR-0068 §3): it reads core's
 * feature registry and writes `src/generated/features.ts`, one method per
 * feature type, typed with core's own input types — and the reference pages
 * under `docs/api/features/`, one per type (ADR-0068 §6).
 *
 * Nothing here is hand-maintained. Doc comments and pages come from the input
 * schemas' `.describe()` texts (with the defaults in them), so a new feature or
 * input reaches the API and its docs by running the script; an input without a
 * description is an error, and `generated.test.ts` fails when the checked-in
 * files are out of date ("run pnpm api:generate").
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { documentFeatures, type FeatureDefinition, z } from '@extrudo/core';
import { exampleCall, methodName, PREAMBLE, SKETCH_TYPE } from './example-calls';
import { featurePage, featuresIndex } from './pages';

/** The repository root, four levels up from `packages/api/src`. */
const ROOT = dirname(dirname(dirname(dirname(fileURLToPath(import.meta.url)))));

/** Where the generated file goes, relative to this module. */
export const GENERATED_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  'generated/features.ts',
);

/** Where the generated reference pages go, relative to the repository root. */
export const DOCS_DIR = join(ROOT, 'docs/api/features');

/**
 * The names `Design` itself has, which a generated method may not take: a
 * feature type named after one of them gets a different method name, or none.
 */
export const RESERVED_NAMES: readonly string[] = [
  'add',
  'create',
  'doc',
  'feature',
  'from',
  'getParameter',
  'group',
  'move',
  'notices',
  'origin',
  'parameter',
  'ref',
  'remove',
  'removeParameter',
  'rename',
  'setParameter',
  'state',
  'suppress',
  'toFile',
  'toJSON',
  'transaction',
  'validate',
];

/** One input of a feature, as the generator reads it. */
export interface InputDoc {
  name: string;
  /** Required by the schema, so the method's `inputs` is required too. */
  required: boolean;
  /** The schema's `.describe()` text, which the doc comment repeats. */
  description: string;
  /** What a call may pass, as the reference's type column reads it. */
  type: string;
  /** The reference kinds, for a `ref` input: `profile`, `face`, … */
  kinds?: string[];
  /** The choice the description names after "Default ", when it names one. */
  fallback?: string;
}

export interface FeatureDoc {
  type: string;
  label: string;
  category: string;
  inputs: InputDoc[];
  /** The face roles the kernel names this feature's faces with (ADR-0068 §4). */
  faceRoles: InputDoc[];
}

/** The text of `generated/features.ts`, as Biome wants it on disk. */
export function generate(): string {
  const features = readFeatureDocs();
  const methods = features.filter((feature) => feature.type !== SKETCH_TYPE);
  for (const feature of methods) {
    const name = methodName(feature.type);
    if (RESERVED_NAMES.includes(name)) {
      throw new Error(
        `The feature type "${feature.type}" wants the method name "${name}", which Design already has: give it another in METHOD_NAMES.`,
      );
    }
  }
  const lines = [
    `/**`,
    ` * GENERATED by \`pnpm api:generate\` (ADR-0068 §3) — do not edit.`,
    ` *`,
    ` * One method per feature type in core's registry (\`documentFeatures()\`), typed`,
    ` * with core's own input types in their plain form (\`PlainInputs<BoxInputs>\`:`,
    ` * \`'40 mm'\`, a face reference, \`true\`), and the list \`d.add(type, inputs)\` takes a type`,
    ` * from. The doc comments come from the input schemas' descriptions, defaults`,
    ` * included; run the script after a feature or an input changes.`,
    ` *`,
    ` * \`sketch\` has no method here: a sketch is made with a builder, not with an`,
    ` * inputs object, so its name is kept for that. A type whose name Design already`,
    ` * has is renamed: Remove and Move become \`removeBodies\` and \`moveBodies\`.`,
    ` */`,
    '',
    `import type {`,
    ...[...new Set(methods.map((f) => inputTypeName(f.type)))].sort().map((name) => `  ${name},`),
    `} from '@extrudo/core';`,
    // In the order Biome's organize-imports wants them, so the file it writes
    // needs no fixing afterwards.
    `import type { Design, FeatureOptions } from '../design';`,
    `import type { FeatureHandle } from '../handles';`,
    `import type { FeatureInputValue, PlainInputs } from '../inputs';`,
    `import type { LineHandle } from '../sketch';`,
    '',
    `/** Every feature type \`Design.add\` takes, in the registry's order. */`,
    `export const FEATURE_TYPES = [`,
    ...features.map((feature) => `  '${feature.type}',`),
    `] as const;`,
    '',
    `/** A feature type of \`FEATURE_TYPES\`. */`,
    `export type FeatureType = (typeof FEATURE_TYPES)[number];`,
    '',
    `/** The generated methods' one-line descriptions, shared with the Script editor. */`,
    `export const FEATURE_METHOD_DESCRIPTIONS: Readonly<Record<string, string>> = {`,
    ...methods.map(
      (feature) =>
        `  ${methodName(feature.type)}: ${JSON.stringify(`${feature.label} (${feature.category}): one feature of the timeline.`)},`,
    ),
    `};`,
    '',
    ...faceRoleTypes(features),
    '',
    `/** What the generated methods need from a design: \`add\`, and nothing else. */`,
    `export interface FeatureMethodTarget {`,
    `  add(type: string, inputs?: FeatureInputValue, options?: FeatureOptions): FeatureHandle;`,
    `}`,
    '',
    `/** One method per feature type, the doc comments from the input schemas. */`,
    `export interface FeatureMethods {`,
    ...methods.flatMap(methodDeclaration),
    `}`,
    '',
    `/**`,
    ` * The methods themselves, bound to a design by its constructor. Each is \`add\``,
    ` * for its own type, so the inputs are checked by the same schema either way.`,
    ` */`,
    `export function featureMethods(design: FeatureMethodTarget): FeatureMethods {`,
    `  return {`,
    ...methods.flatMap((feature) => [
      `    ${methodName(feature.type)}: (${signature(feature)}, options?: FeatureOptions) =>`,
      `      design.add('${feature.type}', inputs, options) as FeatureHandle<'${feature.type}'>,`,
    ]),
    `  };`,
    `}`,
    '',
    ...exampleFunction(features),
  ];
  return format(`${lines.join('\n')}\n`);
}

/**
 * The example calls of the reference pages, as one function (ADR-0068 §6): the
 * preamble every page shows, then one call per feature type. This is what keeps
 * the examples true — `tsc` checks this file, `docs.test.ts` runs the function
 * against a real `Design` — and the pages print the very same lines.
 */
function exampleFunction(features: FeatureDoc[]): string[] {
  return [
    `/**`,
    ` * One example call per feature type, as the reference pages show them`,
    ` * (ADR-0068 §6). The preamble below is on every page; this function runs all`,
    ` * of it, so \`tsc\` checks the examples and \`docs.test.ts\` runs them.`,
    ` */`,
    `export function featureExamples(d: Design): void {`,
    // The preamble's first line creates the design; here it arrives as the
    // parameter, so the rest of it is what follows.
    ...PREAMBLE.slice(1).map((line) => (line ? `  ${line}` : '')),
    ...features
      .filter((feature) => feature.type !== SKETCH_TYPE)
      .flatMap((feature) => ['', `  // ${feature.label}.`, `  ${exampleCall(feature)}`]),
    '',
    `  // Sketch.`,
    ...exampleCall({
      type: SKETCH_TYPE,
      label: 'Sketch',
      category: 'sketch',
      inputs: [],
      faceRoles: [],
    })
      .split('\n')
      .map((line) => `  ${line}`),
    `  void [d, plate, shaft, s, guide, profile, sections, line, face, edge, vertex, corner, body, step, plan, other];`,
    `}`,
  ];
}

/** The generated file as it is on disk, or `undefined` when there is none. */
export function generatedOnDisk(): string | undefined {
  return existsSync(GENERATED_PATH) ? readFileSync(GENERATED_PATH, 'utf8') : undefined;
}

/** The features the generator reads, in the registry's order. */
export function readFeatureDocs(): FeatureDoc[] {
  return documentFeatures().list().map(readFeature);
}

/**
 * The generated reference pages (ADR-0068 §6), as paths relative to the
 * repository root and their text: one per feature type under
 * `docs/api/features/`, and the index that lists them by category.
 */
export function docPages(): Map<string, string> {
  const features = readFeatureDocs();
  const pages = new Map<string, string>([['docs/api/features/README.md', featuresIndex(features)]]);
  features.forEach((feature, order) => {
    pages.set(`docs/api/features/${feature.type}.md`, featurePage(feature, order));
  });
  return pages;
}

/**
 * A generated page as it is on disk, or `undefined` when the file is not there
 * (the staleness test's way of telling a fresh feature from a missing page).
 */
export function docOnDisk(path: string): string | undefined {
  const file = join(ROOT, path);
  return existsSync(file) ? readFileSync(file, 'utf8') : undefined;
}

/**
 * Writes the generated file and every reference page: what
 * `pnpm api:generate` does. Returns the paths it wrote, the generated file
 * first.
 */
export function writeGenerated(): string[] {
  const text = generate();
  writeFileSync(GENERATED_PATH, text);
  mkdirSync(DOCS_DIR, { recursive: true });
  const pages = docPages();
  for (const [path, page] of pages) writeFileSync(join(ROOT, path), page);
  return [GENERATED_PATH, ...pages.keys()];
}

/** One feature's inputs, with the descriptions the doc comments need. */
function readFeature(definition: FeatureDefinition): FeatureDoc {
  const schema = z.toJSONSchema(definition.inputsSchema) as JsonSchema;
  const required = schema.required ?? [];
  const inputs = Object.entries(schema.properties ?? {}).map(([name, property]) => {
    if (!property.description) {
      throw new Error(
        `The input "${name}" of feature type "${definition.type}" has no description: add .describe() to it in packages/core and run pnpm api:generate again.`,
      );
    }
    return {
      name,
      required: required.includes(name),
      description: property.description,
      ...readInput(property),
    };
  });
  return {
    type: definition.type,
    label: definition.label,
    category: definition.category,
    inputs,
    faceRoles: (definition.faceRoles ?? []).map((role) => ({
      name: role.pattern,
      required: true,
      description: role.description,
      type: 'face role',
    })),
  };
}

/** What core's JSON schema form of a stored input says about it. */
interface JsonSchema {
  properties?: Record<string, JsonProperty>;
  required?: string[];
}

/** One property of an inputs schema: its description and its stored shape. */
interface JsonProperty {
  description?: string;
  type?: string;
  properties?: Record<string, { const?: string; enum?: string[] }>;
  input?: { kind?: string; unit?: string; kinds?: string[] };
}

/**
 * The reference's type column and reference kinds for one input, read off the
 * stored shape the schema holds: `kind` says what the input is (`expr`, `ref`,
 * `enum`, `bool`, `file`, `labels`, `sketchData`, `code`) and the metadata says the unit
 * and the reference kinds. What a call passes is the plain value of each (ADR-0068 §3).
 */
function readInput(property: JsonProperty): { type: string; kinds?: string[]; fallback?: string } {
  const stored = property.properties?.kind?.const;
  const fallback = fallbackOf(property.description ?? '');
  switch (stored) {
    case 'expr':
      return { type: 'string | number | ParameterHandle', fallback };
    case 'ref':
      return { type: 'GeomRef | GeomRef[]', kinds: property.input?.kinds, fallback };
    // An enum whose values come from elsewhere (an OpenSCAD import's variable
    // names, ADR-0071 §5) lists none: any string the schema's pattern takes.
    case 'enum': {
      const values = property.properties?.value?.enum ?? [];
      return { type: values.length ? values.map((v) => `'${v}'`).join(' | ') : 'string', fallback };
    }
    case 'bool':
      return { type: 'boolean', fallback };
    case 'file':
      return { type: 'string (an attachment ID)', fallback };
    // A pattern's skipped instances (P4-12): the position labels themselves.
    case 'labels':
      return { type: 'string[]', fallback };
    case 'sketchData':
      return { type: 'SketchData', fallback };
    // A Script's source (P5-02): the text itself.
    case 'code':
      return { type: 'string', fallback };
    default:
      return { type: property.type ?? 'unknown', fallback };
  }
}

/**
 * The default an input's description names — "Default one-side." → "one-side" —
 * which is where the schemas' defaults live in prose. `undefined` when it names
 * none: the input is optional and what it does is what the description says.
 */
function fallbackOf(description: string): string | undefined {
  const match = /Default ([^.]+)\.\s*$/.exec(description);
  const value = match?.[1];
  return value ? value.replace(/^(the|its|a) /, '') : undefined;
}

/**
 * The face roles of every type that has them, as the type of
 * `handle.face(role)`: a role with `<…>` becomes a template literal, so
 * `handle.face('cap:end')` and `handle.face(`side:${line.id}`)` both check and
 * a role the feature never names doesn't (ADR-0068 §4).
 */
function faceRoleTypes(features: FeatureDoc[]): string[] {
  const withRoles = features.filter((feature) => feature.faceRoles.length > 0);
  return [
    `/** The face roles each feature type names its faces with (ADR-0068 §4). */`,
    `export interface FeatureFaceRoles {`,
    ...withRoles.flatMap((feature) => [
      `  /** ${feature.label}: ${feature.faceRoles.map((role) => `\`${role.name}\``).join(', ')}. */`,
      `  ${feature.type}: ${roleType(feature.faceRoles.map((role) => role.name))};`,
    ]),
    `}`,
    '',
    `/**`,
    ` * The role a feature of type \`T\` takes: its own roles where it lists them, and`,
    ` * any string where it names no face of its own (a transform, Offset Face, a`,
    ` * Draft — a role the kernel can't resolve is a lost reference, so a wrong one`,
    ` * is a visible error).`,
    ` */`,
    `export type FaceRoleName<T extends string> = T extends keyof FeatureFaceRoles`,
    `  ? FeatureFaceRoles[T]`,
    `  : string;`,
  ];
}

/** A list of role patterns as a union of string and template literal types. */
function roleType(patterns: readonly string[]): string {
  return [...new Set(patterns)].map(roleTypeOf).join(' | ');
}

/**
 * One role pattern as a type: `side:<curve>` becomes `` `side:${string}` ``, and
 * `cap:end` stays `'cap:end'`, so `handle.face(role)` checks both.
 */
function roleTypeOf(pattern: string): string {
  if (!pattern.includes('<')) return `'${pattern}'`;
  // biome-ignore lint/suspicious/noTemplateCurlyInString: a TS type, not a template.
  return `\`${pattern.replace(/<[^>]*>/g, '${string}')}\``;
}

/** The interface's one method, as lines, with the inputs and the face roles. */
function methodDeclaration(feature: FeatureDoc): string[] {
  const parameters = feature.inputs.some((input) => input.required) ? 'inputs' : 'inputs?';
  const roles = feature.faceRoles.flatMap((role) => [
    `   * - \`${role.name}\` — ${role.description}`,
  ]);
  return [
    `  /**`,
    `   * ${feature.label} (${feature.category}): one feature of the timeline.`,
    `   *`,
    ...feature.inputs.map((input) => `   * @param inputs.${input.name} ${input.description}`),
    ...(roles.length > 0
      ? [`   *`, `   * The faces it makes, as \`handle.face(role)\` takes them:`, ...roles]
      : []),
    `   */`,
    `  ${methodName(feature.type)}(${parameters}: PlainInputs<${inputTypeName(feature.type)}>, options?: FeatureOptions): FeatureHandle<'${feature.type}'>;`,
  ];
}

/** The method's own parameters, with the default for a feature that needs none. */
function signature(feature: FeatureDoc): string {
  return feature.inputs.some((input) => input.required) ? 'inputs' : 'inputs = {}';
}

/**
 * The type of a feature's inputs, which is core's own: `<Type>Inputs` for the
 * PascalCase type name, as every feature module in core names it. A feature
 * whose inputs are built in a loop (Fillet's eight sets, Chamfer's) has one
 * record type for all of them, and that is what this picks.
 */
function inputTypeName(type: string): string {
  return `${type.charAt(0).toUpperCase()}${type.slice(1)}Inputs`;
}

/**
 * Runs Biome over the generated text, so the file on disk is what `pnpm lint`
 * wants and regenerating it changes nothing.
 */
function format(text: string): string {
  const binary = join(ROOT, 'node_modules/@biomejs/biome/bin/biome');
  const result = spawnSync(process.execPath, [binary, 'format', '--stdin-file-path=features.ts'], {
    input: text,
    encoding: 'utf8',
  });
  if (result.status !== 0) {
    throw new Error(`Biome couldn't format the generated file: ${result.stderr || result.error}`);
  }
  return result.stdout;
}
